---
- name: Install PostgreSQL
  apt:
    name: [postgresql, postgresql-contrib, python3-psycopg2]
    state: present
    update_cache: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Create user
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "ALL"
    trust_id_auth: yes

- name: Allow local connections
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host all all 127.0.0.1/32 md5"
  notify: restart postgresql
